apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
  labels:
    "gslab": lamp
  annotations:
    volume.aplha.kubernetes.io/storage-class: longhorn
spec:
  resources:
    requests:
      storage: "1Gi"
  volumeName: "pvc-test"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    "gslab" : lamp
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: rootpw
         - name: MYSQL_USER
           valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: user
         - name: MYSQL_PASSWORD
           valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
         - name: MYSQL_DATABASE
           value: gsLab     
        livenessProbe:
         tcpSocket:
          port: 3306
        ports:
        - containerPort: 3306
        volumeMounts:
         - mountPath: /var/lib/mysql
           subPath: data
           name: database
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: database
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
   "gslab": lamp
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    protocol: TCP
  type: ClusterIP
