apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
  namespace: 2-tier-appp  
  labels:
    "gslab": lamp
  annotations:
    volume.aplha.kubernetes.io/storage-class: longhorn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: pvc-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 2-tier-appp  
  name: mysql
  labels:
    "gslab" : lamp
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        volumeMounts:
         - mountPath: /var/lib/mysql
           subPath: data
           name: database
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: database
---
apiVersion: v1
kind: Service
metadata:
  namespace: 2-tier-appp  
  name: mysql
  labels:
   "gslab": lamp
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    protocol: TCP
  type: ClusterIP
